### ISSUE TITLE
Angular 10 Issues AudioTrackList & VideoTrackList

### ISSUE THREAD

**Issue by lashisu** [videogular/ngx-videogular#18] opened 2020-07-20 15:48 UTC
### Description
*Getting error*

### Expected Behavior
*Should run the app without any error*

### Actual Behavior
*Getting the issues*

`ERROR in node_modules/ngx-videogular/lib/core/vg-media/i-media-element.d.ts:17:27 - error TS2304: Cannot find name 'AudioTrackList'.

17     readonly audioTracks: AudioTrackList;
                             ~~~~~~~~~~~~~~
node_modules/ngx-videogular/lib/core/vg-media/i-media-element.d.ts:139:27 - error TS2304: Cannot find name 'VideoTrackList'.

139     readonly videoTracks: VideoTrackList;
                              ~~~~~~~~~~~~~~
node_modules/ngx-videogular/lib/core/vg-media/vg-media-element.d.ts:5:24 - error TS2304: Cannot find name 'AudioTrackList'.

5     get audioTracks(): AudioTrackList;
                         ~~~~~~~~~~~~~~
node_modules/ngx-videogular/lib/core/vg-media/vg-media-element.d.ts:42:18 - error TS2304: Cannot find name 'VideoTrackList'.

42     videoTracks: VideoTrackList;
                    ~~~~~~~~~~~~~~`

### Attachments
![image](https://user-images.githubusercontent.com/1376383/87957817-67193380-cace-11ea-94e0-b47813405f0f.png)

**Comment by shanehsu** [comment] 2020-07-20 16:58
Are those defined in `dom.d.ts`? Maybe [importing dom in TypeScript config](https://stackoverflow.com/questions/51883220/what-is-dom-for-in-the-lib-array-in-the-tsconfig-json-file-in-angular/51883511#51883511) would help?

**Comment by IxquitilisSaid** [comment] 2020-07-20 17:14
Like I commented on #17, `ngx-videogular` is not the same as `@videogular/ngx-videogular`
The latter ships the correct typings since I added them after lib.dom silently removed them a couple of months ago

**Comment by IxquitilisSaid** [comment] 2020-07-20 17:16
Marking and closing it since it's a duplicate of #17

**Closed by IxquitilisSaid** 2020-07-20 17:16 UTC
Labels: duplicate
