### ISSUE TITLE
Type 'HTMLVideoElement' is missing the following properties from type 'IMediaElement': audioTracks, msAudioCategory, msAudioDeviceType, msGraphicsTrustStatus, and 13 more.

### ISSUE THREAD

**Issue by harry9345** [videogular/ngx-videogular#54] opened 2021-01-21 13:21 UTC
### Description
Hi 
I am totally new to Angular. 
I am trying to show a live stream  with the help of ngx-videogular and I am pretty sure I have done all the steps

### Expected Behavior
 It should show the video

### Steps to Reproduce

` <video
          [vgMedia]="media"
          #media
          id="singleVideo"
          preload="auto"
          crossorigin
        >
          <source
            src="http://demo.unified-streaming.com/video/tears-of-steel/tears-of-steel.ism/.m3u8"
            type="video/mp4"
          />
        </video>`
### Attachments

![Screen Shot 2021-01-21 at 3 02 52 PM](https://user-images.githubusercontent.com/58728417/105355367-b74a8d00-5bfa-11eb-8789-b7f4b7682f24.png)

![Screen Shot 2021-01-21 at 3 10 26 PM](https://user-images.githubusercontent.com/58728417/105355459-dcd79680-5bfa-11eb-8e65-73e84a42f015.png)

| **Image Title** |
| --- |
| (https://media.giphy.com/media/143vPc6b08locw/giphy.gif) |
| Image description |

**Comment by IxquitilisSaid** [comment] 2021-01-21 14:14
Duplicate of videogular/videogular2#904

**Closed by IxquitilisSaid** 2021-01-21 14:14 UTC

**Comment by Mayk98** [comment] 2022-05-25 19:25
@IxquitilisSaid link don't works

**Comment by rycastaneda** [comment] 2022-05-27 07:45
also getting this error

**Comment by Elecash** [comment] 2022-06-08 10:45
@Mayk98 @rycastaneda @joharzmn I've enabled again issues in the old repository, you can navigate to the issue now.

**Comment by joharzmn** [comment] 2022-06-08 11:05
@Elecash Got the solution for this problem but now I am facing another issue. 

```
TypeError: Cannot read properties of undefined (reading 'subscriptions')
    at VgOverlayPlayComponent.onPlayerReady (videogular-ngx-videogular-overlay-play.mjs:33:1)
```

```html
<vg-player>
  <vg-overlay-play vgFor="my-video"></vg-overlay-play>

  <video #media [vgMedia]="$any(media)" height="500px" width="500px" poster="" id="singleVideo" preload="auto" controls>
      <source src="http://static.videogular.com/assets/videos/videogular.mp4" type="video/mp4">
  </video>
</vg-player>

```

**Comment by joharzmn** [comment] 2022-06-08 11:07
@Elecash Nevermind, `id` and `vgFor` was not matching that's why I was getting the error. 
Thanks for the help
